# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScMon < Formula
  desc "sc-mon monitors the status of a Snapchain node."
  homepage "https://github.com/vrypan/sc-mon"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vrypan/sc-mon/releases/download/v0.1.3/sc-mon_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "b1224da48ca51766c3c3930789eaa0618e93c1659e41b99e9b56c75107f3607d"

      def install
        bin.install "sc-mon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vrypan/sc-mon/releases/download/v0.1.3/sc-mon_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "0f654a4259efae022d6841047d795d5eaf9e151680dc9a3c20e3319b5d929bff"

      def install
        bin.install "sc-mon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/sc-mon/releases/download/v0.1.3/sc-mon_Linux_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "1894737962c8a741b837093fc8cfb3a160b4933ddfe36dadb4982cab1080aebf"
      def install
        bin.install "sc-mon"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/sc-mon/releases/download/v0.1.3/sc-mon_Linux_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "07e9cd1b6016a111cd18440ffb969351382969cb584e5dae71b9ee5ef21c4349"
      def install
        bin.install "sc-mon"
      end
    end
  end

  def caveats
    <<~EOS
      sc-mon --help
    EOS
  end

  test do
    system "#{bin}/sc-mon version"
  end
end
