# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScMon < Formula
  desc "sc-mon monitors the status of a Snapchain node."
  homepage "https://github.com/vrypan/sc-mon"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vrypan/sc-mon/releases/download/v0.1.2/sc-mon_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "b6261b6e72922aceecc5940ec8cdfeea91af246d4f95317b8da2ceb340b87e8d"

      def install
        bin.install "sc-mon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vrypan/sc-mon/releases/download/v0.1.2/sc-mon_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "204ce296ebc489e56e2047591bb064b646541dcc9da09133e50ba019e0811352"

      def install
        bin.install "sc-mon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/sc-mon/releases/download/v0.1.2/sc-mon_Linux_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "491c2e8d925ff652442c8e8b65e00d35da764eaebdae3cc34065680015b83805"
      def install
        bin.install "sc-mon"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/sc-mon/releases/download/v0.1.2/sc-mon_Linux_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "e3d52f0999094558f41d9d5fdb5884876a5cfb377ca61b17108d75e7befcc10b"
      def install
        bin.install "sc-mon"
      end
    end
  end

  def caveats
    <<~EOS
      sc-mon --help
    EOS
  end

  test do
    system "#{bin}/sc-mon version"
  end
end
